version: "3.8"

services:
  pairdrop:
    image: "lscr.io/linuxserver/pairdrop:latest"
    container_name: pairdrop
    restart: unless-stopped
    environment:
      - PUID=1000   # UID chạy ứng dụng
      - PGID=1000   # GID chạy ứng dụng
      - TZ=Asia/Ho_Chi_Minh
    expose:
      - "3000"   # expose nội bộ cho Dokploy, không cần publish port ra ngoài
