version: "3.8"

services:
  pairdrop:
    image: "lscr.io/linuxserver/pairdrop:latest"
    container_name: pairdrop
    restart: unless-stopped
    environment:
      - PUID=1000   # UID để chạy ứng dụng
      - PGID=1000   # GID để chạy ứng dụng
      - TZ=Asia/Ho_Chi_Minh   # Múi giờ
    ports:
      - "5555:5555" # Web UI: host 5555 -> container 5555
